# Generated by Django 4.0.3 on 2022-05-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tiempoEjecucion', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='EquiposDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=1000)),
                ('RAG', models.IntegerField()),
                ('informeDePago', models.CharField(max_length=300, null=True)),
                ('informesProcesoSeleccion', models.CharField(max_length=300, null=True)),
                ('llamadosDeAtencion', models.CharField(max_length=45, null=True)),
                ('despido', models.CharField(max_length=300, null=True)),
                ('pregrado', models.CharField(max_length=45, null=True)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('idEquiposDeTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoRest_back.equiposdetrabajo')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoRest_back.rol')),
            ],
        ),
        migrations.CreateModel(
            name='SubActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('tiempoEjecucion', models.DurationField()),
                ('porcentaje', models.FloatField()),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoRest_back.actividad')),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='djangoRest_back.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSubActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoRest_back.subactividad')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoRest_back.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='idEquiposDeTrabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoRest_back.equiposdetrabajo'),
        ),
    ]
