# Generated by Django 4.0.3 on 2022-06-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRest_back', '0002_alter_usuario_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
