# Generated by Django 4.0.3 on 2022-06-11 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRest_back', '0003_alter_rol_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='despido',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idEquiposDeTrabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='djangoRest_back.equiposdetrabajo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='informeDePago',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='informesProcesoSeleccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='llamadosDeAtencion',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pregrado',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
